let cryptoData = [
  {
    id: 1,
    name: "Bitcoin",
    symbol: "BTC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/btc@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 2,
    name: "Ethereum",
    symbol: "ETH",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/eth@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 3,
    name: "Cardano",
    symbol: "ADA",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/ada@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 4,
    name: "Binance Coin",
    symbol: "BNB",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/bnb@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 5,
    name: "Tether",
    symbol: "USDT",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/usdt@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 6,
    name: "XRP",
    symbol: "XRP",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/xrp@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 7,
    name: "Dogecoin",
    symbol: "DOGE",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/doge@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 8,
    name: "Solana",
    symbol: "SOL",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/sol@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 9,
    name: "USD Coin",
    symbol: "USDC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/usdc@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 10,
    name: "Polkadot",
    symbol: "DOT",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/dot@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 11,
    name: "Uniswap",
    symbol: "UNI",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/uni@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 12,
    name: "Terra",
    symbol: "LUNA",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/luna@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 13,
    name: "Binance USD",
    symbol: "BUSD",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/busd@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 14,
    name: "Bitcoin Cash",
    symbol: "BCH",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/bch@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 15,
    name: "Litecoin",
    symbol: "LTC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/ltc@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 16,
    name: "Chainlink",
    symbol: "LINK",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/link@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 17,
    name: "Internet Computer",
    symbol: "ICP",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/icp@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 18,
    name: "Wrapped Bitcoin",
    symbol: "WBTC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/wbtc@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 19,
    name: "Polygon",
    symbol: "MATIC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/matic@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
  {
    id: 20,
    name: "Ethereum Classic",
    symbol: "ETC",
    priceUsd: 0,
    imgsrc: `https://assets.coincap.io/assets/icons/etc@2x.png`,
    status: "normal",
    details: false,
    chartData: {},
  },
];
export default cryptoData;
